### ISSUE TITLE
Move all CI tests to GitHub Actions

### ISSUE THREAD

**Issue by prasanna08** [oppia/oppia-ml#35]
As of now, Oppia-ml has two CI checks: (1) Lint (2) Backend tests. These tests are run on Travis. However, due to limited resources availability on Travis, checks take long time to execute as they spend most of their time being Queued, whereas tests themselves only take a couple of minutes. Hence, these should be moved to GitHub actions to avoid unnecessary delays.

**Comment by seanlip** [comment]
+1 -- this is definitely a good idea! I suggest doing it sooner rather than
later.

**Comment by prasanna08** [comment]
Closing this with #36.
