### ISSUE TITLE
You are using an old version of issue templates. Please update to the new issue template workflow

### ISSUE THREAD

**Issue by Satyam-kumar-yadav** [oppia/oppia-ml#38]
[https://github.com/oppia/oppia-ml/blob/develop/ISSUE_TEMPLATE.md](https://github.com/oppia/oppia-ml/blob/develop/ISSUE_TEMPLATE.md) shows :

![issue_](https://user-images.githubusercontent.com/57104915/102930939-6c3a3e80-44c3-11eb-9fd4-7271f8ce8588.jpg)

[https://help.github.com/articles/about-issue-and-pull-request-templates](https://help.github.com/articles/about-issue-and-pull-request-templates)
[https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser)

**Comment by PasunuriSrinidhi** [comment]
I noticed that the repository is using an old version of the issue templates. The current recommended way to manage issue templates is through the new issue template workflow, which provides more flexibility and control over the templates.

Here are some resources that may be useful for updating the repository to the new workflow:

- https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#creating-issue-templates
- https://docs.github.com/en/issues/tracking-your-work-with-issues/about-automation-for-issues-and-pull-requests-with-query-parameters

I believe that updating to the new workflow would help streamline the issue management process and improve the overall experience

**Comment by seanlip** [comment]
This repository is now archived, so I'm closing this as obsolete.
