### ISSUE TITLE
Implement necessary functions for remote communication

### ISSUE THREAD

**Issue by prasanna08** [oppia/oppia-ml#5]
* Implement `fetch_next_job_request()` and `store_trained_classifier` function for retrieving and storing job requests and result of job requests, respectively.
* Implement `gce_metadata_services` so that `vm_id` and `shared_secret_key` can be retrieved at run-time in production environment.
* Implement `generate_signature()` function for secure communication between VM and Oppia.
* Add constants required by above functions in vmconf.py file.

**Comment by anmolshkl** [comment]
@prasanna08 where should these functions reside? Perhaps, there has to be some kind of service?

**Comment by anmolshkl** [comment]
@prasanna08 I was also thinking about creating milestones and tagging each issue with the particular milestone. This way it would be easier for us to track the progress. How does it sounds?

**Comment by prasanna08** [comment]
@anmolshkl basically each issue is separate GSoC milestone. So we can track progress using issues themselves.

Functions -- Yep they will reside in `services` folder I created. I omitted those details because they are implementation specific. We can talk about names of functions and where each function resides during PR review (I think it is better to discuss them that way).

**Comment by prasanna08** [comment]
Also to test these functions locally (where networking is not possible). We need to use some sort of stub for requests. I was thinking of using [responses](https://pypi.python.org/pypi/responses). There are many other available [here](https://stackoverflow.com/questions/9559963/unit-testing-a-python-app-that-uses-the-requests-library).

The reason I support `responses` is that it is less complex to use. Also its setup is similar to `$httpBackend` used in angularjs. (`httpretty` is more or less same as `responses` but the names `requests` and `responses` suit each other :stuck_out_tongue_winking_eye: )

@seanlip, @anmolshkl, @AllanYangZhou any thoughts on this?

**Comment by seanlip** [comment]
I defer to Anmol and Allan on this.

**Comment by anmolshkl** [comment]
@prasanna08 Ok, but just make sure that a PR is self-contained and does not include so many features that it becomes difficult to review (in general, if your PR grows to be 1000+ lines of code, you should definitely think of splitting it up).

Yep, even I was thinking of something similar. So, I agree with you on using a stub for requests (`responses` looks good).

**Comment by prasanna08** [comment]
Yeah it won't get bigger than that, I guess.
